name: check_java_version

on: [push]

jobs:
  javaVersion:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout respository
        uses: actions/checkout@v2
      - name: List project files and java version
        run: |
              ls -ltr
              java -version
      - name: Checks if node is installed
        run: node -v
      
        
    

  
